#!/bin/bash
# git-up-dirs

# Let the person running the script know what's going on.
echo -e "\n\033[1mPulling in latest changes for all repositories...\033[0m\n"

# Find all directories here - that are at least 1 level down, but don't go any further than 1 directory.
# Go into those directories and pull the repository.
for i in $(find . -maxdepth 1 -mindepth 1 -type d); do
    cd $i;
    if [ -f .git/config ] && [ "`git remote -v`" != "" ]; then
        echo -e "\033[1m"+$i+"\033[0m";
        git pull --all
    fi
    cd ..
done
echo -e "\n-----------------------------\n"

echo -e "\n\033[1mComplete! Do work son!\033[0m\n"
